---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: allure-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 8Gi
  #Replace hostPath for storage cloud solution
  # storageClassName: standard
  storageClassName: local-path 
  hostPath:
    path: /allure/projects

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: allure-secret
type: Opaque
data:
  #echo -n 'my_username' | base64
  SECURITY_USER: bXlfdXNlcm5hbWU=
  #echo -n 'my_password' | base64
  SECURITY_PASS: bXlfcGFzc3dvcmQ=
  #echo -n 'view_user' | base64
  SECURITY_VIEWER_USER: dmlld191c2Vy
  #echo -n 'view_pass' | base64
  SECURITY_VIEWER_PASS: dmlld19wYXNz

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: allure-config-map
data:
  CHECK_RESULTS_EVERY_SECONDS: NONE
  KEEP_HISTORY: "1"
  URL_PREFIX: "/allure-api"
  TLS: "0"
  SECURITY_ENABLED: "0"
  MAKE_VIEWER_ENDPOINTS_PUBLIC: "0"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: allure-config-ui-map
data:
  ALLURE_DOCKER_PUBLIC_API_URL: "http://127.0.0.1:30008"
  ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: "/allure-api"
  URL_PREFIX: "/allure-ui"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure
spec:
  template:
    metadata:
      name: allure-container
      labels:
        type: app
    spec:
      containers:
        - name: allure
          image: "frankescobar/allure-docker-service"
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          securityContext:
            runAsUser: 0
            privileged: false
          envFrom:
            - configMapRef:
                name: allure-config-map
            - secretRef:
                name: allure-secret
          volumeMounts:
            - name: reports-volume
              mountPath: /app/projects
        - name: allure-ui
          image: "frankescobar/allure-docker-service-ui"
          imagePullPolicy: Always
          ports:
            - containerPort: 5252
          securityContext:
            runAsUser: 0
            privileged: false
          envFrom:
            - configMapRef:
                name: allure-config-ui-map
      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: allure-persistent-volume-claim
  replicas: 1
  selector:
    matchLabels:
      type: app

---
apiVersion: v1
kind: Service
metadata:
  name: allure-service-node-port
spec:
  type: NodePort
  ports:
    - name: allure-api
      port: 2020
      targetPort: 5050
      nodePort: 30008
    - name: allure-ui
      port: 3030
      targetPort: 5252
      nodePort: 30009
  selector:
    type: app
