---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      initContainers:
        - name: boxter
          image: mx2542/anti-boxter:latest
          command:
            - "python"
            - "/cache/init-script.py"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /cache/demo
              name: allure-volume
            - name: atop-init-script
              readOnly: true
              mountPath: /cache/init-script.py
              subPath: init-script.py
          env:
            - name: SOURCE
              value: atop
            - name: PROJECT
              value: demo
      containers:
        - name: python
          image: mx2542/tkeel-qa:1.0
          command:
            - "bash"
          args:
            - "-c"
            # - "python /cache/demo/test_demo.py"
            - "echo 123 > /cache/123.log ; sleep 360s"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
          env:
            - name: INFLUXDB_TOKEN
              value: "123"
      restartPolicy: Never
      volumes:
        - name: allure-volume
          persistentVolumeClaim:
            claimName: allure-persistent-volume-claim
        - name: cache-volume
          emptyDir: {}
        - name: atop-init-script
          configMap:
            name: atop-init-script
            items:
              - key: init-script
                path: init-script.py
  backoffLimit: 4
