# 扩展字段:
# 'app.atop.io/type': 'demo', 测试类型, aomaker jmeter ...
# 'app.atop.io/name': '1', 测试任务名称, 唯一
# 'app.atop.io/project': 'demo', 测试项目名称, Gitlab 地址或者 minio 文件夹名称
# 'app.atop.io/cmd': 'python /cache/<project>/test_demo.py', 测试执行命令

# 规范：
# 1.init container 默认将项目下载至目录 /cache/<project>
# 2.测试数据以及日志默认输出目录 /cache, 请根据子目录或者文件名区分日志类型

# shell
# kubectl create configmap atop-init-script --from-file=init_script=scripts/init_script.py -n tink

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-demo

data:
  filebeat.yml: |
    monitoring.enabled: false
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /cache/test_demo_str.log
      fields_under_root: true
      fields: 
        task_type: ${TASK_TYPE}
        task_name: ${TASK_NAME}
        data_type: original

    - type: log
      enabled: true
      paths:
        - /cache/test_demo_json.log
      json.keys_under_root: true
      json.overwrite_keys: true
      fields_under_root: true
      fields: 
        task_type: ${TASK_TYPE}
        task_name: ${TASK_NAME}
        data_type: report

    # setup.ilm.enabled: false
    # setup.template.name: atop
    # setup.template.pattern: "atop-*"

    processors:
      - drop_fields:
          fields: ['agent','ecs','host','log','input',"@metadata"]
          ignore_missing: false

    output.console:
      enabled: false
      pretty: true
    output.kafka:
      enabled: false
      hosts: ["middleware-kafka.tink:9092"]
      topic: '${TASK_TYPE}-${TASK_NAME}'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000
    output.elasticsearch:
      enabled: false
      hosts: ["http://middleware-elasticsearch-master:9200"]
      index: "${TASK_TYPE}"
    output.logstash:
      enabled: true
      hosts: ["middleware-logstash.tink:5044"]

---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    source: atop
    type: demo
    name: "1"
    project: demo
    cmd: python /cache/demo/test_demo.py
  name: demo
spec:
  initContainers:
    - name: boxter
      image: mx2542/anti-boxter:latest
      command:
        - "python"
        - "/cache/init-script.py"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
        - name: atop-init-script
          readOnly: true
          mountPath: /cache/init-script.py
          subPath: init-script.py
      env:
        - name: SOURCE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['source']
        - name: PROJECT
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['project']
  containers:
    - name: python
      image: python:3.9.12-slim
      command:
        - "bash"
      args:
        - "-c"
        - "echo health > /cache/health; $(CMD); rm -rf /cache/health"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
      env:
        - name: CMD
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['cmd']
    - name: filebeat
      image: docker.elastic.co/beats/filebeat:8.3.3
      imagePullPolicy: IfNotPresent
      args:
        - "-e"
        - "-E"
        - "http.enabled=true"
      livenessProbe:
        exec:
          command:
            - cat
            - /cache/health
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: filebeat-config-demo
          readOnly: true
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - mountPath: /cache
          name: cache-volume
  restartPolicy: OnFailure
  volumes:
    - name: filebeat-config-demo
      configMap:
        name: filebeat-config-demo
        items:
          - key: filebeat.yml
            path: filebeat.yml
    - name: atop-init-script
      configMap:
        name: atop-init-script
        items:
          - key: init-script
            path: init-script.py
    - name: cache-volume
      emptyDir: {}
