---
kind: Service
apiVersion: v1
metadata:
  name:  "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app:  "{{ .Release.Name }}-{{ .Chart.Name }}"
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/tink/metrics'
    prometheus.io/port: '8003'
spec:
  selector:
    app:  "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app:  "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app:  "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
{{- if .Values.private }}
      imagePullSecrets:
        - name: regcred
{{- end }}
      containers:
        - name:  "{{ .Release.Name }}-{{ .Chart.Name }}"
          image: "{{ .Values.registry }}/{{ .Values.repository }}/{{ .Values.image }}"
          command:
            - "uvicorn"
          args:
            - "src.main:app"
            - "--reload"
            - "--host=0.0.0.0"
            - "--port=8003"
          ports:
            - containerPort: 8003
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: ELASTICSEARCH_SERVICE_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: atop-globe-config
                  key: elasticsearch_service_hosts