apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXJodWIucWluZ2Nsb3VkLmNvbSI6eyJhdXRoIjoiY1dsdVozUmxjM1JBZVhWdWFXWjVMbU52YlRwNmFIVTRPR3BwWlNFPSJ9LCJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImJYZ3lOVFF5T2pJMU5ESXhNREE0T1RFPSJ9fX0=
type: kubernetes.io/dockerconfigjson
