---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-aomaker
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        enabled: true
        paths:
          - /var/log/containers/${POD_NAME}_tink_aomaker-*.log
        tags: ["aomaker", "log"]

    output.logstash:
      enabled: true
      hosts: ["middleware-logstash.tink:5044"]
