---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-locust
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        paths:
          - /logs/${LOG_NAME}
        tags: ["locust", "log"]

      - type: httpjson
        interval: 1s
        request.method: GET
        request.url: http://${POD_IP}:9090/stats/requests
        tags: ["locust", "stats_requests"]

      - type: httpjson
        interval: 1s
        request.method: GET
        request.url: http://${POD_IP}:9090/tasks
        tags: ["locust", "tasks"]

      - type: httpjson
        interval: 1s
        request.method: GET
        request.url: http://${POD_IP}:9090/exceptions
        tags: ["locust", "exceptions"]

    output.logstash:
      enabled: true
      hosts: ["middleware-logstash.tink:5044"]
