---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-locust
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        enabled: true
        paths:
          - /var/log/containers/${POD_NAME}_tink_locust-*.log
        tags: ["locust", "log"]

      - type: httpjson
        enabled: true
        interval: 1s
        request.method: GET
        request.url: http://127.0.0.1:9090/stats/requests
        tags: ["locust", "stats_requests"]

      - type: httpjson
        enabled: true
        interval: 1s
        request.method: GET
        request.url: http://127.0.0.1:9090/tasks
        tags: ["locust", "tasks"]

      - type: httpjson
        enabled: true
        interval: 1s
        request.method: GET
        request.url: http://127.0.0.1:9090/exceptions
        tags: ["locust", "exceptions"]

    output.logstash:
      enabled: true
      hosts: ["middleware-logstash.tink:5044"]
