---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: "{{ .Release.Name }}"
spec:
  http:
    - name: tink
      match:
        paths:
          - /tink/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
          - CONNECT
          - TRACE
      plugins:
        - name: key-auth
          enable: true
          config:
            key: admin
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /tink/*
              - /*
      websocket: true
      backends:
        - serviceName: "{{ .Release.Name }}"
          servicePort: 8003

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: "{{ .Release.Name }}"
spec:
  scheme: http
  loadbalancer:
    type: roundrobin
